package com.sailpainter;

import com.google.common.collect.ImmutableSet;
import java.util.Set;
import net.runelite.api.gameval.ObjectID;

/** The sail cloth objects a player boat can carry: one per hull size and sail colour. */
final class SailObjects
{
	private static final Set<Integer> IDS = ImmutableSet.of(
		// Raft
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_LINEN,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_CANVAS,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_COTTON,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_BLACK,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_YELLOW,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_PURPLE,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_GREEN,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_BLUE,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_PINK,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_1X3_RED,
		// Skiff
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_LINEN,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_CANVAS,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_COTTON,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_BLACK,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_YELLOW,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_PURPLE,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_GREEN,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_BLUE,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_PINK,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_2X5_RED,
		// Sloop
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_LINEN,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_CANVAS,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_COTTON,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_BLACK,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_YELLOW,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_PURPLE,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_GREEN,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_BLUE,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_PINK,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_RED,
		ObjectID.SAILING_BOAT_SAIL_KANDARIN_3X8_PIRATE
	);

	private SailObjects()
	{
	}

	static boolean isSail(int id)
	{
		return IDS.contains(id);
	}
}
